spring:
  cloud:
    config:
      server:
            git:    
                uri:file:https://github.com/Bablu682/sample-config  
          #file://C:/Users/cprajaba/Documents/workspace-sts-3.7.3.RELEASE/sample-config 

server:
  port: 8899
